### ISSUE TITLE
Update SCSS grammar

### ISSUE THREAD

**Issue by MikeJerred** [microsoft/vscode-css-languageservice#181]
I'm not sure if this is the right repository, but there are several issues with how vscode handles linting and syntax highlighting of scss files e.g.:

* https://github.com/microsoft/vscode/issues/81943
* https://github.com/microsoft/vscode/issues/78974

I did see a reference to [atom/language-sass ](https://github.com/atom/language-sass) in the source code (for vscode), but that repository has been dead for over a year.

**Comment by alexr00** [comment]
Since there are already issues for this (microsoft/vscode#81943, microsoft/vscode#78974) those are the best ones to up-vote. If you have other specific issues, please feel free to open them in the microsoft/vscode repository. If there is a better supported grammar than atom/language-sass then please do mention in! I am happy to consider switching to a better maintained grammar.
