### ISSUE TITLE
Unknown property: dominant-baseline in svg texts

### ISSUE THREAD

**Issue by pguijarr** [microsoft/vscode-css-languageservice#215]
## System:
 - OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (2) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
 - Memory: 881.58 MB / 7.79 GB
 - Container: Yes
 - Shell: 3.1.2 - /usr/bin/fish
## Binaries:
 - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
 - Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
 - npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
## npmPackages:
 - styled-components: ^5.1.0 => 5.1.0

## Reproduction

![image](https://user-images.githubusercontent.com/57676540/82143379-b9767380-9843-11ea-8571-ff87e2bcae1f.png)

## Expected Behavior
Property should be found 
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline
## Actual Behavior
![image](https://user-images.githubusercontent.com/57676540/82143379-b9767380-9843-11ea-8571-ff87e2bcae1f.png)

**Comment by aeschli** [comment]
I think the issue is with the ts-styled-plugin: https://github.com/microsoft/typescript-styled-plugin/issues/115

**Comment by natevw** [comment]
@aeschli Why would the issue be with the plugin? AFAICT it relies on the language services provided **here** to know about CSS properties.

So information about this property should be added to src/data/webCustomData.ts in *this* library, no?

**Comment by natevw** [comment]
The spec for this property can be found at either https://www.w3.org/TR/SVG11/text.html#DominantBaselineProperty (per SVG 1.1) or https://drafts.csswg.org/css-inline/#propdef-dominant-baseline (per CSS draft).

Here's a first draft of what probably needs to be added:

```
{
    "name": "dominant-baseline",
    "values": [
        {
            "name": "auto",
            "description": "Equivalent to alphabetic in horizontal writing modes and in vertical writing modes when text-orientation is sideways. Equivalent to central in vertical writing modes when text-orientation is mixed or upright."
        },
        {
            "name": "text-bottom",
            "description": "Use the text-under baselines."
        },
        {
            "name": "alphabetic",
            "description": "Use the alphabetic baselines."
        },
        {
            "name": "ideographic",
            "description": "Use the ideographic-under baselines."
        },
        {
            "name": "middle",
            "description": "Use the x-middle baselines; except under text-orientation: upright (where the alphabetic and x-height baselines are essentially meaningless) use the central baseline."
        },
        {
            "name": "central",
            "description": "Use the central baselines."
        },
        {
            "name": "mathematical",
            "description": "Use the math baselines."
        },
        {
            "name": "hanging",
            "description": "Use the hanging baselines."
        },
        {
            "name": "text-top",
            "description": "Use the text-over baselines."
        }
    ],
    "syntax": "auto | text-bottom | alphabetic | ideographic | middle | central | mathematical | hanging | text-top",
    "relevance": TODO,
    "description": "Specifies the dominant baseline, which is the default baseline type used to align content within the box.",
    "restrictions": [
        "enum"
    ]
}
```

However, as I went to see what the `relevance` property was about I saw at the top of the webCustomData file that it is perhaps generated (or at least was at one time) by https://github.com/microsoft/vscode-custom-data/tree/master/web-data — so it's unclear if I would submit a patch to the file here or if this is something that needs to get fixed yet further upstream (as opposed to *downstream* which @aeschli implies but seems to be wrong).

**Comment by aeschli** [comment]
The hover shown in the screenshot shows that the error is generated by `ts-styled-plugin`.

But you are right, the `vscode-css-languageservice` also doesn't know of `dominant-baseline`. It's because it is a SVG attribute and we currently don't have these in our css data. We track that in https://github.com/microsoft/vscode/issues/85828

I see that @octref played around with that in the SVG sample at https://github.com/microsoft/vscode-custom-data/blob/master/samples/svg. Pine, do you remember the outcome there? Do we (should we) publish that?

**Comment by octref** [comment]
@aeschli https://github.com/microsoft/vscode/issues/66053, the outcome was not to include SVG support in the core as most people don't hand-write SVG.

**Comment by natevw** [comment]
Bummer. This isn't even about what generates the SVG. I have a lot of generated inline SVG and one of my **CSS style rules** targeting that have been flashing red at me for years now because the CSS language service does not include all valid CSS properties :-(

**Comment by willmtemple** [comment]
> most people don't hand-write SVG

@octref I agree with @natevw that this isn't about generating SVG but styling it. I am using React to create interactive SVG elements and would like to use CSS to set the dominant-baseline attribute (and others that should be applied based on classes) within my application, or otherwise I would have to go through my codebase with hundreds of uses of the `<text>` tag and add the attribute to all of them.

I've also been just living with some files that are never free of warnings for a couple of years because there are valid properties that just aren't recognized.

**Comment by jebeck** [comment]
I just ran into this today. I'm a data visualization engineer, and I hand-write SVG in the vast majority of my applications. It's very common in the data viz world. Yes, I suppose we aren't "most people," but there are a fair number of us out there. (Usually I do use React inline styles but in my current project it makes more sense to style some elements with CSS in order to have well-factored code.) Would really appreciate it if the decision to exclude all SVG properties could be revisited!

**Comment by natevw** [comment]
Thanks @jebeck, I didn't want to complain too much because I thought maybe I was the only odd one generating SVGs myself via Preact (or even weirder mechanisms like Django templates…).

But thinking in terms of data viz, I remembered it was [D3](https://github.com/d3/d3) that got me started doing that! So to say "most people don't hand-write SVG" — when a library with almost 100K stars and over 200K "used by" on GitHub pretty much is **all about** generating custom SVG without Inkscape/Illustrator/Sketch or whatever the maintainers here are imagining — isn't at all accurate.

@octref Where would be the most productive context to discuss this? I'm assuming `dominant-baseline` isn't the only CSS feature this applies to, and as I found in https://github.com/microsoft/vscode-css-languageservice/issues/215#issuecomment-734987840 it's not even clear where a patch would need to be requested. OTOH the ticket at https://github.com/microsoft/vscode/issues/66053 seems overly broad and I don't want to clutter it with just some missing properties unknown to this CSS language service.

**Comment by nakhleh** [comment]
+1 on this. Agree with @natevw, I am running into this because I'm using d3js, which is very mainstream and serves as a compelling counter-example to the idea that "people don't hand-write SVG".

**Comment by dirk-bester** [comment]
Also using d3 and I cannot even type svg tab to create an svg element. It is as if it is not part of html according to VSCode. I don't care about file types, I just want it to work and expand if I type it with the Emmet expansion key.

Why can it not just be more keywords in the html section? That would just transparently work. It can even be under an optional setting so it does not bother people that never use SVG.

Willing to do the work if someone points me at where to go.

**Comment by lukaszlew** [comment]
Is there a way to at least disable the warning?

**Comment by natevw** [comment]
I suspect someone might just need to track down the actual repo or data source and open an outright pull request there! No guarantees it would necessarily be accepted, but seems a more likely way of making any progress on this. It's been a while but iirc it wasn't even 100% obvious (to me as an outsider/end-user) where VS Code gets its list of known properties from.

**Comment by jimbojw** [comment]
Just ran into this today. Same as others, using D3 for custom data visualization. Wanted to style some `<text>` by setting the `alignment-baseline`. Getting an error in VS Code that it's an "Unknown property".

Is there a workaround to at least silence the warning?

**Comment by aeschli** [comment]
The setting `css.lint.unknownProperties` allows you to completly turn off warnings for unknown properties.
Or you can allow `alignment-baseline` with the setting
`"css.lint.validProperties": [ "alignment-baseline" ]`

**Comment by byronigoe** [comment]
Instead of editing the settings.json file manually, you can use the VSCode UI:
![Image](https://github.com/user-attachments/assets/9496418e-b7a5-4844-adfa-00b5b5b24305)
