### ISSUE TITLE
Support CSS nesting

### ISSUE THREAD

**Issue by BenjaminAster** [microsoft/vscode-css-languageservice#300]
The [CSS Nesting Module 1](https://drafts.csswg.org/css-nesting-1/) "introduces the ability to nest one style rule inside another, with the selector of the child rule relative to the selector of the parent rule. This increases the modularity and maintainability of CSS stylesheets". Chromium's ["Implement css-nesting-1" issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1095675) is the [second most starred CSS issue on Chromium Monorail](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3ECSS&colspec=Summary%20Stars&sort=-stars). Chromium [has just implemented experimental CSS nesting support](https://bugs.chromium.org/p/chromium/issues/detail?id=1095675#c13) and the CSSWG [confirmed that the syntax will not change any more](https://developer.chrome.com/blog/help-css-nesting-results/#:~:text=The%20CSSWG%20has%20discussed%20the%20results%20and%20has%20decided%20to%20move%20forwards%20with%20%40nest.%20This%20unblocks%20the%20syntax%20issue%2C%20enabling%20the%20%40nest%20spec%20to%20move%20forward.). Even though CSS nesting is not yet supported in any stable version of a mayor browser, it is already usable with a PostCSS plugin, and, as mentioned above, in Chrome Canary with experimental web platform features enabled.

Related issue on [microsoft/vscode](https://github.com/microsoft/vscode): [#147824](https://github.com/microsoft/vscode/issues/147824)

**Comment by GauravB159** [comment]
Is anyone working on this? I'm not sure how big a change it would be, but I'd love to contribute

**Comment by nilaallj** [comment]
NB: Despite the claim that the current version of the CSS Nesting Module 1 is the final one, the spec got a [new draft version published on October 28](https://drafts.csswg.org/css-nesting/). That seems to be the version Chrome Canary uses.

The main difference in the draft version is that the `@nest` rule has been dropped in favour of operators (`>`, `~` and `+`) and selector characters (`.`, `#` and `:`), meaning that the ampersand is only necessary when a nested selector does not begin with its parent selector. This is quite a significant change from the earlier version.

[A separate PostCSS plugin](https://www.npmjs.com/package/@csstools/postcss-nesting-experimental) has been released for the new spec.

Since the latest version of the spec is still in draft stage, this is probably not the right time to start working on an implementation in VS Code. However, since nesting likely will radically change how many developers write CSS, this should definitely not be slept on once it reaches the stable browsers.

**Comment by samwillis** [comment]
CSS Nesting was shipped in [Chrome 112](https://chromestatus.com/feature/5800613594529792) which will be going stable next week (29th March).

It is also in the current [Safari Tech Preview](https://webkit.org/blog/13813/try-css-nesting-today-in-safari-technology-preview/).

All indications are the spec is final with it being in both Chrome and highly likely to ship in the next stable Safari.

**Comment by romainmenke** [comment]
I think this is done, but maybe I overlooked something in https://github.com/microsoft/vscode-css-languageservice/pull/345

Maybe ok to close and people can report anything missing as a new issue?

**Comment by altrusl** [comment]
CSS nesting is working in VS Code  but syntax highlighting is broken

**Comment by aeschli** [comment]
Closing as nesting is implemented in this service. VS Code still has highlight issues but that's unrelated to the service.

@Stan-Stani You can file a separate issue, but in general we are very tolerant when validating, leaving it to linters to do the full validation. Correctly validating CSS is quite challenging, and users don't like false positives
