### ISSUE TITLE
format *.vue style like unocss/tailwindcss hover:bg-red-400 got blank space

### ISSUE THREAD

**Issue by focussing** [microsoft/vscode-css-languageservice#333]
As Johnson Chu suggested;

The results here are consistent with formatting .scss in VSCode, I suggest you open an issue with https://github.com/microsoft/vscode-css-languageservice.

Please this one: `https://github.com/vuejs/language-tools/issues/1448`

**Comment by demiro** [comment]
It was working fine for me until I updated to latest vscode today ... any idea how to fix it?

**Comment by moracabanas** [comment]
I am also posting from #[1448](https://github.com/vuejs/language-tools/issues/1448)
This is really braking development
This are the reasons we are opening issue here:

One of the most popular stacks (Vue Nuxt3 Tailwind) is broken by the fact CSS is bad formatted. The formatter introduced undesirable spaces on save, braking the main use of Volar autoformat tooling.

![image](https://user-images.githubusercontent.com/4382333/233554068-6df0c096-5921-46da-9961-483422a36f54.png)

Because Volar developers are not able to fix the issue, people is patching our tooling with Prettier which is so opinionated formatter. Some people don't like it, we want to report the issue so we get a chance to be taken in account and fixed.

Thanks!

**Comment by holygekko** [comment]
I'm having the same problem :(

**Comment by romainmenke** [comment]
See : https://github.com/beautify-web/js-beautify/issues/2012

This is not something that can be solved in this packages.
Must be fixed upstream.

**Comment by bitwiseman** [comment]
Please comment the upstream issue with the *text* that is problematic (not an image of the text).

**Comment by Itemshopp** [comment]
@bitwiseman Closed Pull Requester [#2142](https://github.com/beautify-web/js-beautify/pull/2142) here. This is the situation I faced months ago. The exact problem as the issue [#2012](https://github.com/beautify-web/js-beautify/issues/2012) within a Vue file 

Suppose : 

Example.vue Before :
```
<script>...</script

<template>...</template>

<style>

   .button
   {
       @apply flex flex-col lg:flex-row space-y-3 lg:space-x-12 items-start;
   }
   
</style>
```

React like this : 

Example.vue After :
```
<script>...</script

<template>...</template>

<style>

   .button
   {
       @apply flex flex-col lg: flex-row space-y-3 lg:space-x-12 items-start;
   }
   
</style>
```

Like the first element @apply thinks it is a property and adds an additional space to the first commas it finds.

This behavior breaks the Vue file, and the actual way to make rid of it is to turn off css fixes in vue files.

I suppose the correction you applied should make the work. But the context is different compared to a "simple" `.css` file.

Hope this helps.

**Comment by focussing** [comment]
Any  idea when this is solved? It is still very annoying

**Comment by bitwiseman** [comment]
It should be fixed now in the upstream project (Thanks @Itemshopp !).  This extension will need to pull in the new version.  
If you'd like to help, please test your code by formatting it using https://beautifier.io .  If you see problems, file them with the upstream project so that they can be addressed (hopefully soon).

**Comment by romainmenke** [comment]
@aeschli This issue was resolved and can be closed.
see : https://github.com/microsoft/vscode-css-languageservice/commit/1ded897e653d5129bdc4c372917d6580d7ae22c3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R24

**Comment by aeschli** [comment]
Thanks!
