### ISSUE TITLE
Add a guide to setup development workflow.

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode-css-languageservice#42]
Hi,

It isn't mentioned anywhere as to how someone can develop a version locally and test it against a local vscode version. 

Here are the things needed.
1. How to use the local instance of the extension.
2. How to make sure when you update your extension vscode's watch picks up that change and rebuilds.
3. How to use debuggers.

I only know about 1. which is, 
- Make sure your extension directory and vscode code directory reside side by side.
```
somewhere-on-your-pc/
    -vscode-css-languageservice
    -vscode
```
and then in **/vscode/extensions/css/server** and run `npm run install-service-local`.

I can't figure out 2 and 3 however. Help required.

**Comment by aeschli** [comment]
Nothing special about 2. When developing inside vscode (e.g. in the extensions/css) we use `npm run watch` to keep JavaScript files up to date. Sometime a restart of that is required when d.ts files in node_modules change.
For 3:
- open VSCode on the `extensions/css` folder. 
- In the debug viewlet use 'Launch extension'. This starts an extension host instance in debug mode. Breakpoints in the client folder can be reached.
- To reach breakpoint in the server part:
   - In the extension host instance, open a css file
   - In the main VSCode, run 'Attach Language Server'

**Comment by praveenpuglia** [comment]
Does `2` also work with a local installation of the service as well? (`npm run install-service-local`). I see that the files do get changed on the vscode side when i keep a watch( `npm run watch`) on my languageservice repo but that doesn't trigger any build on vscode side unless i modify some other file from `vscode/src` directory.

**Comment by praveenpuglia** [comment]
I made a screencast following your instructions but still can't get the debugger in server to work.
https://goo.gl/photos/YhVixNEL3bTx74ns9

**Comment by aeschli** [comment]
`npm run watch` does not track files in node_modules. So after running`npm run install-service-local` you have to restart `npm run watch`.

What you do in the video looks correct. I think the problem is that the breakpoint to 'cssParser' needs to be set in `/server/node_modules/vscode-css-languageservice/lib/parser/cssParser.js`.
To debug the css parsing I always use mocha tests. That gives you a nice debugging experience. If you have VSCode open on the `vscode-css-languageservice` repo we have the 'Unit Tests' launch.
